CREATE TABLE IF NOT EXISTS selection_gate_shadow (
  article_id text NOT NULL,
  revision integer NOT NULL,
  source_name text NOT NULL,
  source_kind text NOT NULL,
  source_tier text NOT NULL,
  score_model text NOT NULL,
  score_prompt_version text NOT NULL,
  threshold integer NOT NULL,
  first_score integer NOT NULL,
  second_score integer,
  final_score integer,
  selected_by_score boolean,
  gate_status text NOT NULL,
  gate_decision text,
  gate_confidence double precision,
  gate_answer jsonb,
  gate_model text,
  gate_receipt_id bigint,
  gate_usage jsonb,
  error text,
  created_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  PRIMARY KEY (article_id, revision)
);
